language: rust
dist: trusty

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  - CXX=g++-7

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
