[package]
name = "breakpad"
version = "0.1.0"
authors = ["Jan Michael Auer"]
build = "build.rs"

[build-dependencies]
gcc = "0.3"

[dependencies]
error-chain = "0.10"

[dev-dependencies]
difference = "1.0"
